CREATE TABLE IF NOT EXISTS habits (
id SERIAL PRIMARY KEY,
name TEXT NOT NULL,
description TEXT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS logs (
id SERIAL PRIMARY KEY,
habit_id INTEGER NOT NULL,
date DATE NOT NULL,
done BOOLEAN DEFAULT false,
FOREIGN KEY (habit_id) REFERENCES habits(id) ON DELETE CASCADE
);
